spring:
  application:
    name: register-center
server:
  port: 10086
eureka:
  client:
    serviceUrl:
      defaultZone: http://reg.xianlinyi.club:10086/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
